#!/usr/bin/env node
// Regenerates FINDINGS.md from the current catalogue.
//
// The data stays sober so it can be cited. This file is where the data gets to
// be loud. Every number is computed, never written by hand - which means the
// findings cannot drift from the dataset, and a refresh can change the
// leaderboards on its own.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const doc = JSON.parse(await readFile(join(ROOT, 'data', 'models.json'), 'utf8'));
const M = doc.models;

const usd = (v) => (v == null ? '—' : `$${v}`);
const table = (head, rows) =>
  [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

/* ---- 1. price spread across modes of a single model ---- */
const spreads = M.map((m) => {
  const inputs = Object.entries(m.pricing.modes)
    .map(([mode, r]) => [mode, r?.input])
    .filter(([, v]) => typeof v === 'number' && v > 0);
  if (inputs.length < 2) return null;
  const lo = inputs.reduce((a, b) => (b[1] < a[1] ? b : a));
  const hi = inputs.reduce((a, b) => (b[1] > a[1] ? b : a));
  return { id: m.id, lo, hi, ratio: hi[1] / lo[1] };
})
  .filter(Boolean)
  .sort((a, b) => b.ratio - a.ratio);

/* ---- 2. batch dearer than standard ---- */
const batchTax = M.map((m) => {
  const b = m.pricing.modes.batch?.input;
  const s = m.pricing.modes.standard?.input;
  return b != null && s != null && b > s ? { id: m.id, b, s, pct: ((b - s) / s) * 100 } : null;
}).filter(Boolean).sort((a, b) => b.pct - a.pct);

/* ---- 3. cache priced in an unresolved unit ---- */
const schrodinger = M.filter(
  (m) => m.pricing.cache_model === 'unknown' && m.pricing.modes.standard?.cache_read != null,
);
const impossibleWrites = M.filter((m) => {
  const s = m.pricing.modes.standard ?? {};
  return s.cache_write_5m != null && s.input != null && s.cache_write_5m < s.input;
}).sort((a, b) => a.pricing.modes.standard.cache_write_5m - b.pricing.modes.standard.cache_write_5m);

/* ---- 4. phantom tariffs: a priced mode you cannot actually buy ---- */
const phantoms = M.filter((m) =>
  (m.notes ?? []).some((n) => n.startsWith('PHANTOM')),
);

/* ---- 5. silent behaviour changes ---- */
const silent = M.flatMap((m) =>
  (m.notes ?? []).filter((n) => n.startsWith('SILENT CHANGE')).map((n) => ({ id: m.id, n })),
);

/* ---- 6. hard breaks ---- */
const breaks = new Map();
for (const m of M) {
  for (const [k, v] of Object.entries({ ...(m.params ?? {}), ...(m.features ?? {}) })) {
    if (v === 'rejected') {
      if (!breaks.has(k)) breaks.set(k, []);
      breaks.get(k).push(m.id);
    }
  }
}

/* ---- 7. tokenizer babel ---- */
const tok = {};
for (const m of M) tok[m.tokenizer.family] = (tok[m.tokenizer.family] ?? 0) + 1;
const tokRows = Object.entries(tok).sort((a, b) => b[1] - a[1]);

/* ---- 8. deprecation blackout ---- */
const withShutdown = M.filter((m) => m.lifecycle?.shutdown_date);

const out = `# Findings

*Generated by \`src/findings.mjs\` on every build. Every number here is computed from
\`data/models.json\` — nothing in this file is written by hand, so it cannot drift from
the data. A catalogue refresh can rewrite these leaderboards on its own.*

**${doc.coverage.models} models · ${doc.coverage.tokenizer_families} tokenizer families · ${doc.coverage.param_cells_known_pct}% of the capability matrix verified**

---

## 🎭 The Same Model, Wildly Different Bills

Upstream catalogues list **${doc.coverage.upstream_entries} entries** for **${doc.coverage.models} actual models**. The other
**${doc.coverage.folded_price_variants}** are pricing *modes* — identical weights, different tariff — listed as if they
were separate products. Rank a leaderboard on that feed and you count the same model
three times, at whichever price flatters the chart.

Biggest spread between the cheapest and dearest way to call one model:

${table(['Model', 'Cheapest', 'Dearest', 'Spread'],
  spreads.slice(0, 12).map((s) => [
    `\`${s.id}\``, `${usd(s.lo[1])} (${s.lo[0]})`, `${usd(s.hi[1])} (${s.hi[0]})`, `**${s.ratio.toFixed(1)}×**`,
  ]))}

## 💸 The Batch Tax

"Batch is 50% off" is folk wisdom, not a rule. **${batchTax.length} models cost *more* in batch
mode than standard** — because the "standard" price is the cheapest routed host while
batch is one specific host's tariff.

${batchTax.length ? table(['Model', 'Standard', 'Batch', 'Penalty'],
  batchTax.slice(0, 12).map((b) => [`\`${b.id}\``, usd(b.s), usd(b.b), `**+${b.pct.toFixed(0)}%**`])) : '_None in the current catalogue._'}

## 🐈 Schrödinger's Cache

Cache economics dominate real agent cost, and the data is a mess. Of ${M.length} models,
**${doc.coverage.priced_with_cache_read} publish a cache read price, only ${doc.coverage.priced_with_cache_write} publish a cache write price.**

Worse, the ones that publish aren't using the same unit. **${schrodinger.length} models** have a
cache price whose billing model is unresolved.

And **${impossibleWrites.length} models report a cache *write* that costs less than a normal read** — an
impossible shape for a one-off write fee. It's almost certainly per-hour storage rent
flattened into the same column as Anthropic-style write premiums. Anyone computing
"cost with caching" from that feed is quietly wrong.

${table(['Model', 'Input', '"Cache write"', 'Ratio'],
  impossibleWrites.slice(0, 10).map((m) => {
    const s = m.pricing.modes.standard;
    return [`\`${m.id}\``, usd(s.input), usd(s.cache_write_5m), `${(s.cache_write_5m / s.input).toFixed(2)}×`];
  }))}

## 👻 Phantom Tariffs

Prices for things you cannot actually buy. Resellers keep serving a tariff after the
provider has withdrawn the feature.

${phantoms.length ? phantoms.map((m) => `- \`${m.id}\` — ${(m.notes.find((n) => n.startsWith('PHANTOM')) ?? '').replace('PHANTOM PRICING UPSTREAM: ', '')}`).join('\n') : '_None recorded yet._'}

## 🤫 Silent Changes

The errors are survivable. These are worse — same code, different behaviour, no error,
different bill.

${silent.length ? silent.map((s) => `- \`${s.id}\` — ${s.n.replace('SILENT CHANGE: ', '')}`).join('\n') : '_None recorded yet._'}

## 💥 Hard Breaks

Parameters that return an **error** on at least one model. Every one of these is
verified against first-party documentation — the build refuses to ship a \`rejected\`
claim sourced from a reseller.

${breaks.size ? table(['Parameter / feature', 'Models that reject it'],
  [...breaks.entries()].sort((a, b) => b[1].length - a[1].length)
    .map(([k, v]) => [`\`${k}\``, `${v.length} — ${v.map((x) => x.split('/')[1]).join(', ')}`])) : '_None recorded yet._'}

## 🗼 Tokenizer Babel

**${tokRows.length} distinct tokenizer families.** A token is a different amount of text in each one,
which is why \`$/Mtok\` is not a comparable unit and every leaderboard that ranks on it
is ranking on sand.

${table(['Tokenizer family', 'Models'], tokRows.map(([k, v]) => [`\`${k}\``, String(v)]))}

**Measured so far: ${doc.coverage.tokenizers_measured} of ${tokRows.length}.** This is the highest-leverage unfinished work in the
repo, and it needs no API key — just a shared corpus and a local tokenizer.

## 🌑 Deprecation Blackout

**${withShutdown.length} of ${M.length} models publish a shutdown date.**

Providers bury the one date that can break your production on a deadline you did not
choose. Upstream sentinel values like \`2098-12-31\` are stripped rather than passed
through as real dates.

${withShutdown.length ? table(['Model', 'Shuts down'], withShutdown.map((m) => [`\`${m.id}\``, m.lifecycle.shutdown_date])) : ''}

---

*Found something wrong? That's the point — open an issue with a source URL. Provenance
means we can tell exactly which source was wrong, and when.*
`;

await writeFile(join(ROOT, 'FINDINGS.md'), out);

/* ---- shields.io endpoint badges, self-updating from the data ---- */
const badge = (label, message, color) => JSON.stringify({ schemaVersion: 1, label, message, color });
await mkdir(join(ROOT, 'data', 'badges'), { recursive: true });
const badges = {
  models: badge('models', String(doc.coverage.models), 'blue'),
  coverage: badge('capability matrix', `${doc.coverage.param_cells_known_pct}% verified`,
    doc.coverage.param_cells_known_pct > 75 ? 'green' : doc.coverage.param_cells_known_pct > 40 ? 'yellow' : 'orange'),
  tokenizers: badge('tokenizer families', String(doc.coverage.tokenizer_families), 'purple'),
  measured: badge('tokenizers measured', `${doc.coverage.tokenizers_measured}/${doc.coverage.tokenizer_families}`,
    doc.coverage.tokenizers_measured ? 'green' : 'red'),
  spend: badge('api spend', '$0.00', 'brightgreen'),
};
for (const [name, body] of Object.entries(badges)) {
  await writeFile(join(ROOT, 'data', 'badges', `${name}.json`), body + '\n');
}

console.log(`FINDINGS.md    : ${spreads.length} spreads, ${batchTax.length} batch-tax, ${impossibleWrites.length} impossible writes, ${silent.length} silent changes`);
console.log(`badges         : ${Object.keys(badges).length} written`);
